### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 239573049** [lobehub/lobe-ui#227] opened 2024-12-03 02:57 UTC
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/user-attachments/assets/3ac1283f-8d56-4070-b4ae-e93db9d7296e)
Code编辑器的鼠标选择出现字体混乱

**Comment by arvinxx** [comment] 2024-12-05 04:59
duplicate of https://github.com/lobehub/lobe-ui/issues/200

**Closed by arvinxx** 2024-12-05 04:59 UTC
Labels: 🐛 Bug
